### ISSUE TITLE
npm2deb search graceful-fs giving error

### ISSUE THREAD

**Issue by divatemangesh** [LeoIannacone/npm2deb#106]
I am running this command  on docker image of  debian:sid 

```

root@f2e7e0e7914d:/# npm2deb search graceful-fs

Looking for similar package:
  node-graceful-fs (4.1.11-1) (unstable)

Looking for existing repositories:
Traceback (most recent call last):
  File "/usr/bin/npm2deb", line 7, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3/dist-packages/npm2deb/scripts.py", line 138, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/npm2deb/scripts.py", line 156, in search_for_module
    _helper.search_for_repository(node_module)
  File "/usr/lib/python3/dist-packages/npm2deb/helper.py", line 35, in search_for_repository
    (url_base, repo, module)).read()
  File "/usr/lib/python3.6/urllib/request.py", line 223, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open
    response = meth(req, response)
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error
    return self._call_chain(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

```

**Comment by rajudev** [comment]
I tried replicating the issue. And it is replicating as it in containers.
also the package is already done and is available in repository.
 ```
root@ee8c88271ffb:/# apt show node-graceful-fs
Package: node-graceful-fs
Version: 4.1.11-1
Priority: optional
Section: javascript
Maintainer: Debian Javascript Maintainers <pkg-javascript-devel@lists.alioth.debian.org>
Installed-Size: 38.9 kB
Depends: nodejs
Homepage: https://github.com/isaacs/node-graceful-fs
Download-Size: 10.8 kB
APT-Manual-Installed: no
APT-Sources: http://deb.debian.org/debian sid/main amd64 Packages
Description: drop-in replacement improving the Node.js fs module
```
