### ISSUE TITLE
`man` field can be a list: AttributeError: 'list' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by kapouer** [LeoIannacone/npm2deb#20]
npm2deb create npm

```
  File "/usr/lib/python3/dist-packages/npm2deb/__init__.py", line 103, in create_manpages
    content = _os.path.normpath(self.json['man'])
  File "/usr/lib/python3.5/posixpath.py", line 332, in normpath
    initial_slashes = path.startswith(sep)
AttributeError: 'list' object has no attribute 'startswith'
```

**Comment by kapouer** [comment]
Another way to reproduce:
```
npm2deb create marked-man
Traceback (most recent call last):
  File "/usr/bin/npm2deb", line 7, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3/dist-packages/npm2deb/scripts.py", line 139, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/npm2deb/scripts.py", line 276, in create
    npm2deb.start()
  File "/usr/lib/python3/dist-packages/npm2deb/__init__.py", line 85, in start
    self.create_manpages()
  File "/usr/lib/python3/dist-packages/npm2deb/__init__.py", line 177, in create_manpages
    content = _os.path.normpath(self.json['man'])
  File "/usr/lib/python3.5/posixpath.py", line 333, in normpath
    initial_slashes = path.startswith(sep)
AttributeError: 'list' object has no attribute 'startswith'
```

**Comment by kapouer** [comment]
With version 0.2.6 as well
