### ISSUE TITLE
source location

### ISSUE THREAD

**Issue by nnovikov** [LeoIannacone/npm2deb#21]
I have some exception output in generated files:
```
% cat monocle/node-monocle/debian/watch
version=3
# It is not recommended use fakeupstream. Please investigate more.
# Origin url: module.js:457
    throw err;
    ^% cat monocle/node-monocle/debian/watch
version=3
# It is not recommended use fakeupstream. Please investigate more.
# Origin url: module.js:457
    throw err;
    ^

Error: Cannot find module 'github-url-from-git'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at [eval]:1:13
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.exports.runInThisContext (vm.js:77:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:556:32)
    at bootstrap_node.js:357:29
# Take a look at https://wiki.debian.org/debian/watch/
# See also fakeupstream: http://anonscm.debian.org/viewvc/qa/trunk/cgi-bin/fakeupstream.cgi?view=markup
opts=\
dversionmangle=s/\+(debian|dfsg|ds|deb)(\.\d+)?$//,\
filenamemangle=s/.*=// \
 http://qa.debian.org/cgi-bin/fakeupstream.cgi?upstream=npmjs/monocle .*=monocle-(\d.*)\.(?:tgz|tar\.(?:gz|bz2|xz))


Error: Cannot find module 'github-url-from-git'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at [eval]:1:13
    at ContextifyScript.Script.runInThisContext (vm.js:25:33)
    at Object.exports.runInThisContext (vm.js:77:17)
    at Object.<anonymous> ([eval]-wrapper:6:22)
    at Module._compile (module.js:556:32)
    at bootstrap_node.js:357:29
# Take a look at https://wiki.debian.org/debian/watch/
# See also fakeupstream: http://anonscm.debian.org/viewvc/qa/trunk/cgi-bin/fakeupstream.cgi?view=markup
opts=\
dversionmangle=s/\+(debian|dfsg|ds|deb)(\.\d+)?$//,\
filenamemangle=s/.*=// \
 http://qa.debian.org/cgi-bin/fakeupstream.cgi?upstream=npmjs/monocle .*=monocle-(\d.*)\.(?:tgz|tar\.(?:gz|bz2|xz))

```

**Comment by LeoIannacone** [comment]
It looks like you haven't installed `node-github-url-from-git` package

**Comment by nnovikov** [comment]
This package is already present:
```
% sudo apt install node-github-url-from-git
Reading package lists... Done
Building dependency tree       
Reading state information... Done
node-github-url-from-git is already the newest version (1.1.1-1).
node-github-url-from-git set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 8 not upgraded.
```

**Comment by LeoIannacone** [comment]
Please provide more info:
debian version?
which node
node --version
which npm2deb

**Comment by nnovikov** [comment]
```
nnovikov@fe-03-nodejs ~ % apt-cache policy nodejs
nodejs:
  Installed: 6.6.0-1nodesource1~xenial1
  Candidate: 6.6.0-1nodesource1~xenial1
  Version table:
 *** 6.6.0-1nodesource1~xenial1 500
        500 https://deb.nodesource.com/node_6.x xenial/main amd64 Packages
        100 /var/lib/dpkg/status
     4.2.6~dfsg-1ubuntu4.1 500
        500 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages
     4.2.6~dfsg-1ubuntu4 500
        500 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
nnovikov@fe-03-nodejs ~ % lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.1 LTS
Release:	16.04
Codename:	xenial
nnovikov@fe-03-nodejs ~ %  node --version
v6.6.0
nnovikov@fe-03-nodejs ~ % apt-cache policy npm2deb
npm2deb:
  Installed: 0.2.4-1
  Candidate: 0.2.4-1
  Version table:
 *** 0.2.4-1 500
        500 http://archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        100 /var/lib/dpkg/status
nnovikov@fe-03-nodejs ~ % which npm2deb
/usr/bin/npm2deb
nnovikov@fe-03-nodejs ~ % which node   
/usr/bin/node
nnovikov@fe-03-nodejs ~ % dpkg -S /usr/bin/npm2deb
npm2deb: /usr/bin/npm2deb
nnovikov@fe-03-nodejs ~ % ls -l /usr/bin/node
lrwxrwxrwx 1 root root 22 Sep 16 08:07 /usr/bin/node -> /etc/alternatives/node
nnovikov@fe-03-nodejs ~ % ls -l /etc/alternatives/node
lrwxrwxrwx 1 root root 15 Sep 16 08:07 /etc/alternatives/node -> /usr/bin/nodejs
nnovikov@fe-03-nodejs ~ % ls -l /usr/bin/nodejs
-rwxr-xr-x 1 root root 25210528 Sep 15 22:36 /usr/bin/nodejs
nnovikov@fe-03-nodejs ~ % dpkg -S /usr/bin/nodejs
nodejs: /usr/bin/nodejs
nnovikov@fe-03-nodejs ~ % 
```

**Comment by LeoIannacone** [comment]
You're not using a node version provided by the official Ubuntu repository
