### ISSUE TITLE
npm2deb gives error with sshpk module

### ISSUE THREAD

**Issue by pravi** [LeoIannacone/npm2deb#63]
```
pravi@nishumbha:~/forge/debian/webpack$ npm2deb create sshpk
Traceback (most recent call last):
  File "/usr/bin/npm2deb", line 7, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3/dist-packages/npm2deb/scripts.py", line 139, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/npm2deb/scripts.py", line 276, in create
    npm2deb.start()
  File "/usr/lib/python3/dist-packages/npm2deb/__init__.py", line 85, in start
    self.create_manpages()
  File "/usr/lib/python3/dist-packages/npm2deb/__init__.py", line 178, in create_manpages
    content = _os.path.normpath(self.json['man'])
  File "/usr/lib/python3.5/posixpath.py", line 333, in normpath
    initial_slashes = path.startswith(sep)
AttributeError: 'list' object has no attribute 'startswith'
```

**Comment by shanavas786** [comment]
Duplicatet of #20
This issue has already been fixed and does not exist in master branch.
Seems this commit is not available in debian port.

**Comment by pravi** [comment]
@shanavas786 can we merge all pending pull requests and make a new release?

**Comment by shanavas786** [comment]
I can't merge my own PRs until someone with write access reviews and approves.

@psuhailp help please :)

**Comment by psuhailp** [comment]
@shanavas786 : Sorry for the delay. I am working on it

**Comment by shanavas786** [comment]
New version is available in Debian
