### ISSUE TITLE
npm2deb is failing to create deb for css-tree

### ISSUE THREAD

**Issue by pravi** [LeoIannacone/npm2deb#90]
```
$ npm2deb create css-tree
Traceback (most recent call last):
  File "/usr/bin/npm2deb", line 7, in <module>
    sys.exit(main(sys.argv))
  File "/usr/lib/python3/dist-packages/npm2deb/scripts.py", line 138, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/npm2deb/scripts.py", line 273, in create
    npm2deb.start()
  File "/usr/lib/python3/dist-packages/npm2deb/__init__.py", line 71, in start
    self.download()
  File "/usr/lib/python3/dist-packages/npm2deb/__init__.py", line 405, in download
    raise ValueError(exception)
ValueError: Error downloading package css-tree
npm ERR! notarget No compatible version found: css-tree@'*'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["1.0.0-alpha","1.0.0-alpha2","1.0.0-alpha3","1.0.0-alpha4","1.0.0-alpha5","1.0.0-alpha6","1.0.0-alpha7","1.0.0-alpha8","1.0.0-alpha9","1.0.0-alpha10","1.0.0-alpha11","1.0.0-alpha12","1.0.0-alpha13","1.0.0-alpha14","1.0.0-alpha15","1.0.0-alpha16","1.0.0-alpha17","1.0.0-alpha18","1.0.0-alpha19","1.0.0-alpha20","1.0.0-alpha21","1.0.0-alpha22","1.0.0-alpha23","1.0.0-alpha24","1.0.0-alpha25"]
npm ERR! notarget 
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! System Linux 4.12.0-1-amd64
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "pack" "css-tree"
npm ERR! cwd /home/pravi/forge/debian/gitlab/css-tree
npm ERR! node -v v6.11.4
npm ERR! npm -v 1.4.21
npm ERR! code ETARGET
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/pravi/forge/debian/gitlab/css-tree/npm-debug.log
npm ERR! not ok code 0
```

**Comment by shanavas786** [comment]
Again an outdated `npm` issue. It fails to download unstable versions. Works fine with `npm 4.2.0`.

**Comment by pravi** [comment]
@shanavas786 npm install css-tree@1.0.0-alpha25 works. #58 will help as a workaround.

**Comment by shanavas786** [comment]
Yes, I checked it.

**Comment by pravi** [comment]
npm 5.8 is now in unstable and npm2deb create css-tree@1.0.0-alpha25 also works. Closing.
